### ISSUE TITLE
Weight Not Being Removed From Inventory

### ISSUE THREAD

**Issue by kommandantjut** [DefenderVex/helix_plugins#1]
Weight doesn't always get removed from inventory when a player looses an item, i.e the item turns into a spawned world entity.

Below as an example function that causes the weight not to be removed from inventory when used.
```
ITEM.functions.Place = {
	OnRun = function( itemTable )
		local client = itemTable.player

		scripted_ents.Get( "stove" ):SpawnFunction( client, client:GetEyeTraceNoCursor() )
	end
}
```

Any help would be appreciated.

**Comment by DefenderVex** [comment]
Try adding itemTable:DropWeight()
